steps:
  - label: "Build Frontend"
    commands:
      - "cd frontend"
      - "echo \"--- Building Frontend\""
      - "npm install"
      - "npm run build"
      - "echo \"--- Uploading to S3\""
      - "ls -la"
      - "sam --version"
      - "echo \"--- Invalidating CloudFront Cache\""
      - "aws --version"