steps:
  - block: ":rocket: Select Deployment Configuration"
    prompt: "Please select deployment environment and region"
    fields:
      - select: "Environment"
        key: "environment"
        options:
          - label: "Staging"
            value: "staging"
          - label: "Production"
            value: "production"
        required: true
      - select: "AWS Region"
        key: "region"
        options:
          - label: "US East (N. Virginia)"
            value: "us-east-1"
          - label: "US West (Oregon)"
            value: "us-west-2"
          - label: "EU West (Ireland)"
            value: "eu-west-1"
          - label: "Asia Pacific (Singapore)"
            value: "ap-southeast-1"
        required: true

  - label: ":gear: Deploy Infrastructure"
    command: |
      # Get selections from buildkite meta-data
      ENVIRONMENT="$$BUILDKITE_BLOCK_ENVIRONMENT"
      REGION="$$BUILDKITE_BLOCK_REGION"

      # Print selections for confirmation
      echo "Deploying to:"
      echo "Environment: $${ENVIRONMENT}"
      echo "Region: $${REGION}"

      # Execute the generate-pipeline script
      cd infra/cloudformation/frontend-host
      .buildkite/scripts/generate-pipeline.sh "$ENVIRONMENT" "$REGION"
    concurrency: 1
    concurrency_group: "cloudformation-deploy-$${BUILDKITE_BLOCK_ENVIRONMENT}"