steps:
  - block: ":earth_americas: Select AWS Region"
    fields:
      - select: "AWS Region"
        key: "aws-region"
        options:
          - label: "US East (N. Virginia)"
            value: "us-east-1"
          - label: "US West (Oregon)"
            value: "us-west-2"
          - label: "EU West (Ireland)"
            value: "eu-west-1"
          - label: "Asia Pacific (Singapore)"
            value: "ap-southeast-1"
        required: true
      - select: "Environment"
        key: "environment"
        default: "staging"
        options:
          - label: "Staging"
            value: "staging"
          - label: "Production"
            value: "production"
        required: true

  - label: ":gear: Generate CloudFormation Pipeline"
    command: |
      echo "Selected AWS Region: $${BUILDKITE_BLOCK_AWS_REGION}"
      echo "Selected Environment: $${BUILDKITE_BLOCK_ENVIRONMENT}"
      
      # Execute generate-pipeline script with selected values
      cd infra/cloudformation/frontend-host
      .buildkite/scripts/generate-pipeline.sh "$ENVIRONMENT" "$REGION"
    concurrency: 1
    concurrency_group: "cloudformation-$${BUILDKITE_BLOCK_ENVIRONMENT}"