#!/bin/bash

AWS_REGION=$(buildkite-agent meta-data get "AWS_REGION")
ENVIRONMENT=$(buildkite-agent meta-data get "ENVIRONMENT")

echo "Deploying frontend to $ENVIRONMENT in $AWS_REGION"


pwd

./infra/cloudformation/frontend-host/.buildkite/scripts/generate-pipeline.sh $AWS_REGION $ENVIRONMENT