AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ip-lookup-api-lambda

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: staging
    Description: The environment to deploy the stack to
    AllowedValues:
      - staging
      - production

Resources:
  getIpLookupDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}--ip-lookup-api
      Handler: src/handlers/ip-lookup.mjs.getByIdHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{ip}
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
